const data = [
    {
    id: 1,
    title: "MyCare: Designing Human-Centered Care Toolkit",
    courseCode: "00001",
    clinicalType: "Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 30,
    isChecked: false,
    bgColor: false
  },
  {
    id: 2,
    title: "MyCare: Effective Job Training with Job Instruction (JI)",
    courseCode: "00002",
    clinicalType: "Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 10,
    isChecked: false,
    bgColor: false
  },
  {
    id: 3,
    title: "MyCare: The Ant of Standardized Work (SW) for Consistency",
    courseCode: "00003",
    clinicalType: "Non-Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 15,
    isChecked: false,
    bgColor: false
  },
  {
    id: 4,
    title: "MyCare: Introduction to Design Thinking",
    courseCode: "00004",
    clinicalType: "Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 40,
    isChecked: false,
    bgColor: false
  },
  {
    id: 5,
    title: "MyCare: Start and Sustain the Environment",
    courseCode: "00005",
    clinicalType: "Non-Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 20,
    isChecked: false,
    bgColor: false
  },
  {
    id: 6,
    title: "Identifying Waste and Polution in the City",
    courseCode: "00006",
    clinicalType: "Non-Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 20,
    isChecked: false,
    bgColor: false
  },
  {
    id: 7,
    title: "MyCare: Designing Human-Centered Care Toolkit",
    courseCode: "00007",
    clinicalType: "Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 30,
    isChecked: false,
    bgColor: false
  },
  {
    id: 8,
    title: "MyCare: Effective Job Training with Job Instruction (JI)",
    courseCode: "00008",
    clinicalType: "Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 20,
    isChecked: false,
    bgColor: false
  },
  {
    id: 9,
    title: "MyCare: The Ant of Standardized Work (SW) for Consistency",
    courseCode: "00009",
    clinicalType: "Non-Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 15,
    isChecked: false,
    bgColor: false
  },
  {
    id: 10,
    title: "MyCare: Introduction to Design Thinking",
    courseCode: "00010",
    clinicalType: "Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 10,
    isChecked: false,
    bgColor: false
  },
  {
    id: 11,
    title: "MyCare: Start and Sustain the Environment",
    courseCode: "00011",
    clinicalType: "Non-Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 20,
    isChecked: false,
    bgColor: false
  },
  {
    id: 12,
    title: "Identifying Waste and Polution in the City",
    courseCode: "00012",
    clinicalType: "Non-Clinical",
    image: "http://via.placeholder.com/350x250",
    courseOverview: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dapibus elit in elit facilisis luctus. Cras congue maximus est quis dignissim. Nulla eu ante orci. Quisque fermentum purus ut dolor facilisis scelerisque. In gravida nibh nec euismod egestas. Nullam at tincidunt metus. Cras finibus velit non dictum molestie. Ut tincidunt ullamcorper pellentesque. Maecenas in magna et turpis tempus commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut suscipit odio sit amet risus viverra, nec finibus lectus luctus. Aliquam dapibus in nulla eu tristique.",
    preRequisite: "Aenean elementum, metus id sollicitudin pulvinar, est massa dapibus ex, ut viverra sem ex et enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla maximus efficitur nibh, imperdiet imperdiet est bibendum rhoncus. Vestibulum sodales id libero ut sodales. Curabitur vel lacinia purus, at volutpat nulla. Aenean a aliquam nulla, vitae dapibus elit. Curabitur congue turpis sed quam ornare interdum non sed dui. Integer eu odio eu felis lacinia sagittis ut et eros.",
    audience: "Nunc commodo elit sem, eu volutpat justo tempor quis. Pellentesque quis sem massa. Integer eget libero est. Fusce tortor sem, aliquet sed feugiat eget, aliquam eget ligula. In hendrerit mauris eros, nec egestas velit viverra sed. Proin maximus dolor a enim rhoncus mattis. Morbi vel lorem volutpat, commodo tortor a, consectetur risus. Maecenas non gravida mauris. Sed consequat finibus sem et hendrerit. Ut a nulla consectetur, hendrerit orci sollicitudin, ultricies nisl. Sed vel sem nulla.",
    modality: "F2F",
    duration: "1 Day x 3 Hrs",
    price: 15,
    isChecked: false,
    bgColor: false
  }
];

export default data;


